# https://docs.travis-ci.com/user/ci-environment/

git:
  depth: 500

dist: trusty
sudo: false
osx_image: xcode8.3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - clang-4.0
      - clang-format-4.0
      - clang-tidy-4.0

env:
  global:
    - BAZEL_VERSION=0.5.2
    - PATH=/usr/local/opt/llvm/bin:$HOME/bin/:$PATH
    - DISPLAY=:0.0

matrix:
  fast_finish: true
  include:
    - os: linux
    - os: osx
  allow_failures:
    - os: osx

language: cpp
compiler:
  - clang

cache:
  pip: true
  directories:
  - /tmp/.cache/bazel_root
  - /tmp/.cache/bazel_root_analyze

install:
  - git fetch https://github.com/google/xrtl.git master:refs/remotes/origin/master
  - ./tools/ci/travis/install.sh

script:
  - ./tools/ci/travis/lint.sh
  - ./tools/ci/travis/build.sh
  - ./tools/ci/travis/test.sh
  - ./tools/ci/travis/analyze.sh
