# https://docs.travis-ci.com/user/ci-environment/

git:
  depth: 500

dist: trusty
sudo: false
osx_image: xcode8.3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - clang-4.0
      - clang-tidy-4.0

env:
  global:
    - BAZEL_VERSION=0.5.2
    - PATH=$PATH:$HOME/bin/
    - DISPLAY=:0.0

matrix:
  fast_finish: true
  include:
    - os: linux
      env:
        - BAZEL_PLATFORM=linux-x86_64
        - BAZEL_INSTALLER=bazel-$BAZEL_VERSION-jdk7-installer-linux-x86_64.sh
    - os: osx
      env:
        - BAZEL_PLATFORM=darwin-x86_64
        - BAZEL_INSTALLER=bazel-$BAZEL_VERSION-installer-darwin-x86_64.sh

language: cpp
compiler:
  - clang

cache:
  pip: true
  directories:
  - /tmp/.cache/bazel_root

install:
  - ./tools/ci/travis/install.sh

script:
  - ./tools/ci/travis/presubmit.sh
  - ./tools/ci/travis/build.sh
  - ./tools/ci/travis/test.sh
  - ./tools/ci/travis/analyze.sh
