# Description:
#  Android port root. Packages under here match those in the root XRTL package.
#  May use some of the common port files under //xrtl/port/common/.
#
#  Targets:
#  - Android API Level: 23
#  - NDK Version: 14b
#  - Compiler: clang

package(default_visibility = ["//xrtl:internal"])
