# Description:
#  Android port variants of //xrtl/base/ features.

package(default_visibility = ["//xrtl:internal"])

cc_library(
    name = "android_logging_sink",
    srcs = ["android_logging_sink.cc"],
    deps = [
        "//xrtl/base:logging_hdrs",
    ],
)
