# Description:
#  Cross-platform Real-time Rendering Library.

package(default_visibility = [":internal"])

# Restricts most packages to use by //xrtl/... only.
# Selective rules we wish to support to external users are set to
# //visibility:public.
package_group(
    name = "internal",
    packages = [
        "//xrtl/...",
    ],
)
