# Description:
#  Linux port root. Packages under here match those in the root XRTL package.
#  May use some of the common port files under //xrtl/port/common/.
#
#  Targets:
#  - Ubuntu

package(default_visibility = ["//xrtl:internal"])
