# Description:
#  gfx test data.

package(default_visibility = ["//xrtl:internal"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "test_images",
    srcs = [
        "images/grid.png",
        "images/grid_cropped.png",
        "images/triangle.png",
    ],
)
