# Description:
#  Windows port root. Packages under here match those in the root XRTL package.
#  May use some of the common port files under //xrtl/port/common/.
#
#  Targets:
#  - Visual C++: 2017
#  - Windows SDK: 10?

package(default_visibility = ["//xrtl:internal"])
