# Description:
#  Graphics testing utilties.

package(default_visibility = ["//xrtl:internal"])

licenses(["notice"])  # Apache 2.0

cc_library(
    name = "partial_command_encoder",
    testonly = 1,
    hdrs = ["partial_command_encoder.h"],
    deps = [
        "//xrtl/gfx:command_encoder",
    ],
)
