# Description:
#  Utility scripts.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

sh_binary(
    name = "macos_test_runner",
    srcs = ["macos_test_runner.sh"],
)
