# Description:
#  Diff test goldens.

package(default_visibility = ["//xrtl:internal"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "test_files",
    srcs = [
        "data_file.bin",
        "image_file.png",
        "text_file.txt",
    ],
)
