# Description:
#  Golden testdata for gfx testing utilities.

package(default_visibility = ["//xrtl:internal"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "graphics_test_data",
    srcs = [
        "compare_image.png",
    ],
)
