# Description:
#  Golden testdata for gfx testing utilities.

package(default_visibility = ["//xrtl:internal"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "graphics_test_data",
    srcs = [
        "compare_buffer_golden_full.bin",
        "compare_buffer_golden_partial.bin",
        "compare_framebuffer_0.png",
        "compare_framebuffer_1.png",
        "compare_image.png",
    ],
)
