# Description:
#  MacOS port root. Packages under here match those in the root XRTL package.
#  May use some of the common port files under //xrtl/port/common/.
#
#  Targets:
#  - Xcode Version: 8.2
#  - MacOS SDK: 10?
#  - MacOS Version: 10?

package(default_visibility = ["//xrtl:internal"])
